# $FreeBSD$

compute_engine_instance:
  # Image list available via
  # gcloud compute images list --project freebsd-org-cloud-dev --no-standard-images
  platform: freebsd
  image_project: freebsd-org-cloud-dev
  image: freebsd-13-0-release-amd64
  cpu: 8
  memory: 8G
  disk: 40

task:
  timeout_in: 120m
  install_script:
  - sh .cirrus-ci/pkg-install.sh qemu
  setup_script:
  - uname -a
  - df -m
  - pkg --version
  script:
  - sh build.sh
  post_script:
  - df -m
  - du -m -s /usr/obj
