#!/bin/sh

# PROVIDE: oci-setup
# REQUIRE: NETWORKING
# BEFORE: LOGIN

. /etc/rc.subr

: ${oci_setup_enable:="YES"}
: ${oci_setup_list:="py38-cloud-init"}

name="oci_setup"
rcvar=oci_setup_enable
start_cmd="oci_setup_run"
stop_cmd=":"

oci_setup_run()
{
        # Bootstrap and update pkg to ensure synchronization with the repository
        env ASSUME_ALWAYS_YES=YES pkg bootstrap -f | cat
        env ASSUME_ALWAYS_YES=YES pkg update -f | cat

        # Install requested packages, if any
        for package in ${oci_setup_list}; do
                env ASSUME_ALWAYS_YES=YES pkg install ${package} </dev/null |
                    cat
        done

	touch /firstboot
	rm /etc/rc.d/oci-setup
	echo "OK Packages Installed"
	shutdown -p now
}

load_rc_config $name
run_rc_command "$1"
